"""First migration

Revision ID: 6ff98a2655b2
Revises: 
Create Date: 2023-07-06 09:01:07.778976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff98a2655b2'
down_revision = None
branch_labels = None
depends_on = None

insert_role_admin = """
    INSERT INTO roles(id, name, description, created_at, updated_at) 
    SELECT T.* 
    FROM (select 
                '3874cbd1-24ca-4d8e-95e0-b854048400be'::uuid as ID, 
                'admin' as NAME, 
                'admin' as DESCRIPTION,
                '1900-01-01 00:00:00'::TIMESTAMP as created_at,
                '1900-01-01 00:00:00'::TIMESTAMP as updated_at
        ) as T
        LEFT JOIN roles as r ON T.id = r.id
    WHERE r.id is null"""

insert_role_user = """
    INSERT INTO roles(id, name, description, created_at, updated_at) 
    SELECT T.* 
    FROM (select 
                '56599c23-4265-4824-b646-38338ee2d4a6'::uuid as ID, 
                'user' as NAME, 
                'user' as DESCRIPTION,
                '1900-01-01 00:00:00'::TIMESTAMP as created_at,
                '1900-01-01 00:00:00'::TIMESTAMP as updated_at
        ) as T
        LEFT JOIN roles as r ON T.id = r.id
    WHERE r.id is null"""

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )

    op.execute(insert_role_admin)
    op.execute(insert_role_user)

    op.create_table('users',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('account_history',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), server_default='default UA', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_token', sa.String(length=500), server_default='default UT', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('account_history')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###