"""Create roles

Revision ID: 2
Revises:
Create Date:

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2'
down_revision = '1'
branch_labels = None
depends_on = None


insert_role_admin = """
    INSERT INTO roles(id, name, description, created_at, updated_at) 
    SELECT T.* 
    FROM (select 
                '3874cbd1-24ca-4d8e-95e0-b854048400be'::uuid as ID, 
                'admin' as NAME, 
                'admin' as DESCRIPTION,
                '1900-01-01 00:00:00'::TIMESTAMP as created_at,
                '1900-01-01 00:00:00'::TIMESTAMP as updated_at
        ) as T
        LEFT JOIN roles as r ON T.id = r.id
    WHERE r.id is null"""

insert_role_user = """
    INSERT INTO roles(id, name, description, created_at, updated_at) 
    SELECT T.* 
    FROM (select 
                '56599c23-4265-4824-b646-38338ee2d4a6'::uuid as ID, 
                'user' as NAME, 
                'user' as DESCRIPTION,
                '1900-01-01 00:00:00'::TIMESTAMP as created_at,
                '1900-01-01 00:00:00'::TIMESTAMP as updated_at
        ) as T
        LEFT JOIN roles as r ON T.id = r.id
    WHERE r.id is null"""


def upgrade():
    # ### commands made by maks ###
    op.execute(insert_role_admin)
    op.execute(insert_role_user)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
